// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiXqKiQHPBjQyi5Wz41V6guQc3xLr-Hxg',
    appId: '1:799940124037:web:8d3db9b193c83b1628b8ec',
    messagingSenderId: '799940124037',
    projectId: 'minders-dmy-ali-helal',
    authDomain: 'minders-dmy-ali-helal.firebaseapp.com',
    storageBucket: 'minders-dmy-ali-helal.firebasestorage.app',
    measurementId: 'G-SXVZSL63EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSseV5GIwOQW0IgRNvY49-hX3ZzkQAIvw',
    appId: '1:799940124037:android:66e2a6b21eec212b28b8ec',
    messagingSenderId: '799940124037',
    projectId: 'minders-dmy-ali-helal',
    storageBucket: 'minders-dmy-ali-helal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgfgXaWzPXO2tvdqGEK9ro63Lyjb1InhQ',
    appId: '1:799940124037:ios:a405d0c53cb0b21628b8ec',
    messagingSenderId: '799940124037',
    projectId: 'minders-dmy-ali-helal',
    storageBucket: 'minders-dmy-ali-helal.firebasestorage.app',
    iosBundleId: 'com.example.minders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgfgXaWzPXO2tvdqGEK9ro63Lyjb1InhQ',
    appId: '1:799940124037:ios:a405d0c53cb0b21628b8ec',
    messagingSenderId: '799940124037',
    projectId: 'minders-dmy-ali-helal',
    storageBucket: 'minders-dmy-ali-helal.firebasestorage.app',
    iosBundleId: 'com.example.minders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiXqKiQHPBjQyi5Wz41V6guQc3xLr-Hxg',
    appId: '1:799940124037:web:815ef3bc7e38d29428b8ec',
    messagingSenderId: '799940124037',
    projectId: 'minders-dmy-ali-helal',
    authDomain: 'minders-dmy-ali-helal.firebaseapp.com',
    storageBucket: 'minders-dmy-ali-helal.firebasestorage.app',
    measurementId: 'G-3RMPH8P40V',
  );

}